"""add player_expected_points_weekly

Revision ID: 11919bb26697
Revises: d7b5c4e6f566
Create Date: 2026-10-07 10:33:27.249097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11919bb26697'
down_revision: Union[str, Sequence[str], None] = 'd7b5c4e6f566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
